### ISSUE TITLE
Support for point data

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#233] opened 2021-11-15 16:35 UTC
For info, I have added a `fit_pts` method and `fit_pts_func` to certain `Coreg` subclasses in this branch (as I need those rapidly): https://github.com/rhugonnet/xdem/tree/coreg_point_support

As we do not have a preferential support for point data as of now, the implementation is quite restricted: not applicable to many formats, not super consistent. Maybe the right way to go about this would be to add a Class to Geoutils to handle point data at a lower level? I think Fiona/Geopandas takes care of pretty much everything, so it could be simply a `GeoDataframe` object (we'd still need to implement some wrapper methods to facilitate the interface with Raster objects).

So the addition to `Coreg` subclasses require some more thinking to draft a finalized version. Maybe we can discuss this rapidly Wednesday?

**Comment by erikmannerfelt** [comment] 2021-11-17 09:38
This is a duplicate of #134

**Closed** 2022-01-04 09:43 UTC
Labels: duplicate
